config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show, :index]

  post "follow", to: "follows#follow", as: :follow
  delete "follow", to: "follows#unfollow", as: :unfollow
  delete "cancel_request", to: "follows#cancel_request", as: :cancel_request

  post "accept_follow", to: "follows#accept_follow", as: :accept_follow
  delete "decline_follow", to: "follows#decline_follow", as: :decline_follow

  resources :messages, only: [:index, :create]

  resources :invites, only: [:index, :show]
  post "send_invite", to: "invites#send_invite", as: :send_invite
  post "accept_invite/:id", to: "invites#accept_invite", as: :accept_invite
  delete "decline_invite/:id", to: "invites#decline_invite", as: :decline_invite
  
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  after_create_commit -> {
    broadcast_append_later_to sender.pair_id(receiver, :chat_box),
      target: "messages"
  }
  
  def mark_seen
    self.update(has_seen: true, seen_time: DateTime.now)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # include ActionView::RecordIdentifier

  def index
    @chat_users = current_user.users_chatting_with
  
    @user_chatting_with = 
      if params[:receiver]
        User.find(params[:receiver])
      else
        @chat_users.first
      end
  
    @all_messages = current_user.all_messages_with(@user_chatting_with)
  
    @message = current_user.sent_messages.new(receiver: @user_chatting_with)
  end
  
  def create
    if @message = current_user.sent_messages.create(message_params)
    
    else
      redirect_to chat_path, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :receiver_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_chat_box.html.erb
<%= turbo_stream_from current_user.pair_id(user_chatting_with, :chat_box) %>

<div class="chat-box">

  <%# Chat Box Header %>
  <div class="chat-header d-flex justify-content-between py-3 px-3 border-bottom border-2">
    
    <%= render "layouts/shared/user_info", user: user_chatting_with %>

    <div class="d-flex flex-column">

    </div>
  </div>

  <%# Messages %>
  <div class="messages-container">
    <div class="messages d-flex flex-column justify-content-end px-3 py-3" id="messages">
      <%= render partial: "message", collection: all_messages %>
    </div>
  </div>

  <%# Send Message Field %>
  <div class="chat-send">

    <%= form_with model: message, url: messages_path,
          data: {
            controller: "chat",
            action: "turbo:submit-end->chat#clear"
          } do |f| %>
      <div class="d-flex justify-content-between m-3 p-2 border border-2 border-light-subtle rounded-pill bg-white">
        <%= f.text_field :content, placeholder: "Message...", 
              class: "chat-content-field border-0 form-control" %>

        <%= f.hidden_field :receiver_id %>

        <%= f.submit "Send", class: "border-0 bg-white" %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/_chat_user.html.erb
<%= link_to messages_path(receiver: chat_user), 
    class: "#{'selected' if chat_user == user_chatting_with} a-decoration-none" do %>
  <%= render "layouts/shared/user_info", user: chat_user %>
<% end %>

app/views/messages/_chat_user_detail.html.erb
<div class="chat-user-detail">
  <%= image_tag profile_pic(chat_user),
                class: "img-thumbnail rounded-circle" %>

  <div class="d-flex flex-column justify-content-center mx-3">
    <small class="chat-username">
      <%= link_to chat_user, 
                  data: {turbo: false}, 
                  class: "a-decoration-none" do %>
        <%= chat_user.username %>
      <% end %>
    </small>

    <small class="" 
          style="color: rgb(115, 115, 115); font-size: .75rem; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 10rem;">
      Active 5h ago
    </small>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message msg-<%= message.sender_id %>">
  <%= image_tag profile_pic(message.sender),
              class: "img-thumbnail rounded-circle",
              style: "width: 2rem" %>

  <span class="msg-content rounded-pill"><%= message.content %></span>
</div>

app/views/messages/_new_message.html.erb
<div class="new-message modal fade" id="newMessageModal" tabindex="-1" aria-labelledby="newMessageModalLabel" aria-hidden="true" data-controller="new-message">
  <div class="modal-dialog">
    <div class="modal-content" >

      <div class="modal-header">
        <h1 class="modal-title fs-5 w-100 text-center" id="newMessageModalLabel">New message</h1>

        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-search">
        <%= form_with url: users_path, method: :get, 
                data: {
                  new_message_target: "searchForm",
                  turbo_stream: true
                },
                class: "user-search-form" do |f| %>

          <%= f.label :search_query, "To:", class: "fw-bold" %>

          <%= f.hidden_field :search_target, value: :search_user_results %>

          <%= f.text_field :search_query, placeholder: "Search...",
                class: "search-query border-0 flex-grow-1",
                data: { 
                  action: "input->new-message#search",
                  new_message_target: "searchQuery"
                } %>
        <% end %>
      </div>

      <%= form_with url: send_invite_path, method: :post,
            data: { new_message_target: "messageForm" } do |f| %>
        <div class="modal-body d-flex flex-column">

          <ul class="modal-search-results" id="modal-search-results"
              data-new-message-target="searchResults">
            <%= render "search_user_results", users: [] %>
          </ul>

          <%= f.hidden_field :user_id, 
                data: { new_message_target: "messageReceiver" } %>

          <%= f.text_area :message,
                value: "Hi, I would like to chat with you...",
                style: "display: none;",
                class: "message-box",
                data: { new_message_target: "messageBox" } %>
        </div>

        <div class="modal-footer">
          <%= f.submit "Chat", type: "button", disabled: true,
            class: "chat-button btn btn-primary form-control",
            data: { new_message_target: "messageButton",
              action: "click->new-message#submit" } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/messages/_no_messages.html.erb
<div class="no-messages p-3">
  <h4 class="fs-5 text-muted">No messages yet,... Click 
    <%= link_to "here", "#", 
            class: "text-dark",
            data: {
              bs_toggle: "modal",
              bs_target: "#newMessageModal"
            } %>
    to create a new one.
  </h4>
</div>

app/views/messages/_search_user_results.html.erb
<% users.each do |user| %>

    <%= tag.li class: "search-result p-3 d-flex justify-content-between align-items-center",
          data: { 
            action: "click->new-message#setUser",
            username: "#{user.username}",
            user: "#{user.id}"
          } do %>
          
      <div class="user-info d-flex align-items-center">
        <%= image_tag profile_pic(user), 
            class: "img-thumbnail rounded-circle", 
            style: "width: 2.5rem" %>

        <small class="username fw-bold flex-grow-1 ms-3" 
            style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 10rem">
          <%= user.username %>
        </small>
      </div>

      <div class="form-check">
        <input class="form-check-input user-radio" type="radio" name="user-radio"data-new-message-target="radio">
      </div>

    <% end %>
<% end %>

app/views/messages/create.turbo_stream.erb
<#%= turbo_stream.append "messages", @message %>

app/views/messages/index.html.erb
<div class="chat">

  <div class="chat-side border-end border-dark-subtle border-2">

    <%= turbo_stream_from dom_id(current_user, :chat_list) %>
    <div class="d-flex justify-content-between align-items-center p-4">
      <%# Username %>
      <span class="fw-bold fs-4">
        <%= current_user.username %>
      </span>

      <%# New Message Requests %>
      <%= link_to "#", 
            class: "text-dark",
            data: {
              bs_toggle: "modal",
              bs_target: "#newMessageModal"
            } do %>
        <i class="fa-regular fa-pen-to-square fa-xl"></i>
      <% end %>
    </div>

    <%# Chat Users List Header %>
    <div class="d-flex justify-content-between align-items-center py-2 px-4">
      <small class="fw-bold">Messages</small>

      <%# Invite Requests %>
      <%= link_to "Requests", invites_path, class: "fw-bold text-muted" %>
    </div>
    
    <%# List of chat users %>
    <div class="chat-user-list d-flex flex-column" id="chat-user-list">
      <%= render partial: "chat_user", collection: @chat_users,
            locals: { user_chatting_with: @user_chatting_with } %>
    </div>

  </div>

  <% if @chat_users.any? %>
    
    <%= render "chat_box", 
          user_chatting_with: @user_chatting_with, 
          all_messages: @all_messages,
          message: @message %>
  <% else %>

    <%= render "no_messages" %>
  <% end %>
</div>

<%= render "new_message" %>