config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show, :index]

  post "follow", to: "follows#follow", as: :follow
  delete "follow", to: "follows#unfollow", as: :unfollow
  delete "cancel_request", to: "follows#cancel_request", as: :cancel_request

  post "accept_follow", to: "follows#accept_follow", as: :accept_follow
  delete "decline_follow", to: "follows#decline_follow", as: :decline_follow

  resources :messages, only: [:index, :create]

  resources :invites, only: [:index, :show]
  post "send_invite", to: "invites#send_invite", as: :send_invite
  post "accept_invite/:id", to: "invites#accept_invite", as: :accept_invite
  delete "decline_invite/:id", to: "invites#decline_invite", as: :decline_invite
  
end

app/views/layouts/shared/_follow_state.html.erb
<% if current_user.followings.include?(user) %>
  <%= button_to "Unfollow", unfollow_path(user_id: user.id), method: :delete, class: "btn btn-danger", data: {turbo: false} %>
<% elsif current_user.waiting_followings.include?(user) %>
  <%= button_to "Cancel", cancel_request_path(user_id: user.id), method: :delete, class: "btn btn-secondary", data: {turbo: false} %>
<% elsif current_user == user %>
<% else %>
  <%= button_to "Follow", follow_path(user_id: user.id), method: :post, class: "btn btn-primary", data: {turbo: false} %>
<% end %>

app/views/layouts/shared/_user_info.erb
<div class="user-info">
  <%= image_tag profile_pic(user),
                class: "img-thumbnail rounded-circle" %>

  <div class="d-flex flex-column justify-content-center mx-3">
    <small class="chat-username">
      <%= link_to_if local_assigns[:with_link],
                  user, 
                  data: { turbo: false }, 
                  class: "a-decoration-none" do %>
        <%= user.username %>
      <% end %>
    </small>

    <%# <small class="" 
          style="color: rgb(115, 115, 115); font-size: .75rem; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 10rem;">
      Active 5h ago
    </small> %>
  </div>
</div>